{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Billing",
    "version": "1.0.0-beta"
  },
  "paths": {
    "/v1beta/invoices": {
      "get": {
        "tags": [
          "InvoiceService"
        ],
        "summary": "List invoices",
        "operationId": "ListInvoices",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "The limit.",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "description": "The offset.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order.",
            "name": "order",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order by.",
            "name": "order_by",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The start creation date.",
            "name": "start_creation_date",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The end creation date.",
            "name": "end_creation_date",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/invoiceListInvoicesResponse"
            }
          },
          "default": {
            "description": "(empty)",
            "schema": {
              "$ref": "#/definitions/errorError"
            }
          }
        }
      }
    },
    "/v1beta/payments": {
      "get": {
        "tags": [
          "Payment"
        ],
        "summary": "List payments",
        "operationId": "ListPayments",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "The limit.",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "description": "The offset.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order.",
            "name": "order",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order by.",
            "name": "order_by",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The type.",
            "name": "type",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The status.",
            "name": "status",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The start creation date.",
            "name": "start_creation_date",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The end creation date.",
            "name": "end_creation_date",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/paymentListPaymentsResponse"
            }
          },
          "default": {
            "description": "(empty)",
            "schema": {
              "$ref": "#/definitions/errorError"
            }
          }
        }
      }
    },
    "/v1beta/transactions": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "List transactions",
        "operationId": "ListTransactions",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "The limit.",
            "name": "limit",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "description": "The offset.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order.",
            "name": "order",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The order by.",
            "name": "order_by",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The start creation date.",
            "name": "start_creation_date",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The end creation date.",
            "name": "end_creation_date",
            "in": "query"
          },
          {
            "type": "string",
            "description": "The filter for subject.",
            "name": "filter_for_subject",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/transactionListTransactionsResponse"
            }
          },
          "default": {
            "description": "(empty)",
            "schema": {
              "$ref": "#/definitions/errorError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "errorError": {
      "type": "object",
      "title": "Error",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "title": "Error code"
        },
        "data": {
          "type": "string",
          "title": "Additional error description"
        },
        "desc": {
          "type": "string",
          "title": "Error description"
        }
      },
      "example": {
        "code": 0,
        "data": "",
        "desc": ""
      }
    },
    "errorWarning": {
      "type": "object",
      "title": "Warning",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "title": "Warning code"
        },
        "data": {
          "type": "string",
          "title": "Additional warning description"
        },
        "desc": {
          "type": "string",
          "title": "Warning description"
        }
      },
      "example": {
        "code": 0,
        "data": "",
        "desc": ""
      }
    },
    "invoiceInvoice": {
      "type": "object",
      "title": "Invoice",
      "properties": {
        "amount": {
          "title": "The amount",
          "$ref": "#/definitions/invoicePrices"
        },
        "attachment_url": {
          "type": "string",
          "title": "The attachment url"
        },
        "creation_date": {
          "type": "string",
          "title": "The creation date"
        },
        "id": {
          "type": "integer",
          "format": "int32",
          "title": "The id"
        },
        "invoice_number": {
          "type": "string",
          "title": "The invoice number"
        },
        "invoice_url": {
          "type": "string",
          "title": "The invoice url"
        }
      },
      "example": {
        "amount": {
          "product": {
            "currency": "EUR",
            "price": 0
          },
          "reseller": {
            "currency": "EUR",
            "price": 0
          }
        },
        "attachment_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice",
        "creation_date": "2006-09-29 0:00:00",
        "id": 1,
        "invoice_number": "XX123456",
        "invoice_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice"
      }
    },
    "invoiceListInvoicesResponse": {
      "type": "object",
      "title": "ListInvoicesResponse",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "title": "The code"
        },
        "data": {
          "title": "The data",
          "$ref": "#/definitions/invoiceListInvoicesResponseData"
        },
        "desc": {
          "type": "string",
          "title": "The desc"
        },
        "maintenance": {
          "type": "boolean",
          "format": "boolean",
          "title": "The maintenance"
        },
        "warnings": {
          "type": "array",
          "title": "The warnings",
          "items": {
            "$ref": "#/definitions/errorWarning"
          }
        }
      },
      "example": {
        "code": 0,
        "data": {
          "results": [
            {
              "amount": {
                "product": {
                  "currency": "EUR",
                  "price": 0
                },
                "reseller": {
                  "currency": "EUR",
                  "price": 0
                }
              },
              "attachment_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice",
              "creation_date": "2006-09-29 0:00:00",
              "id": 1,
              "invoice_number": "XX123456",
              "invoice_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice"
            }
          ],
          "total": 0
        },
        "desc": ""
      }
    },
    "invoiceListInvoicesResponseData": {
      "type": "object",
      "title": "ListInvoicesResponseData",
      "properties": {
        "results": {
          "type": "array",
          "title": "The results",
          "items": {
            "$ref": "#/definitions/invoiceInvoice"
          }
        },
        "total": {
          "type": "integer",
          "format": "int32",
          "title": "The total"
        }
      },
      "example": {
        "results": [
          {
            "amount": {
              "product": {
                "currency": "EUR",
                "price": 0
              },
              "reseller": {
                "currency": "EUR",
                "price": 0
              }
            },
            "attachment_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice",
            "creation_date": "2006-09-29 0:00:00",
            "id": 1,
            "invoice_number": "XX123456",
            "invoice_url": "https://rest.openprovider.eu/invoice/XX123456?token=\u0026type=invoice"
          }
        ],
        "total": 0
      }
    },
    "invoicePrice": {
      "type": "object",
      "title": "Price",
      "properties": {
        "currency": {
          "type": "string",
          "title": "The currency"
        },
        "price": {
          "type": "number",
          "format": "double",
          "title": "The price"
        }
      },
      "example": {
        "currency": "EUR",
        "price": 0
      }
    },
    "invoicePrices": {
      "type": "object",
      "title": "Prices",
      "properties": {
        "product": {
          "title": "Price in product currency",
          "$ref": "#/definitions/invoicePrice"
        },
        "reseller": {
          "title": "Price in reseller currency",
          "$ref": "#/definitions/invoicePrice"
        }
      },
      "example": {
        "product": {
          "currency": "EUR",
          "price": 0
        },
        "reseller": {
          "currency": "EUR",
          "price": 0
        }
      }
    },
    "paymentListPaymentsResponse": {
      "type": "object",
      "title": "ListPaymentsResponse",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "title": "The code"
        },
        "data": {
          "title": "The data",
          "$ref": "#/definitions/paymentListPaymentsResponseData"
        },
        "desc": {
          "type": "string",
          "title": "The desc"
        },
        "maintenance": {
          "type": "boolean",
          "format": "boolean",
          "title": "The maintenance"
        },
        "warnings": {
          "type": "array",
          "title": "The warnings",
          "items": {
            "$ref": "#/definitions/errorWarning"
          }
        }
      },
      "example": {
        "code": 0,
        "data": {
          "results": [
            {
              "amount": {
                "product": {
                  "currency": "EUR",
                  "price": 0
                },
                "reseller": {
                  "currency": "EUR",
                  "price": 0
                }
              },
              "confirmation_date": "",
              "creation_date": "2006-09-15 14:19:30",
              "id": 123,
              "is_processed": false,
              "method": "",
              "payment_date": "2006-09-15 14:25:30",
              "status": "new",
              "type": "online"
            }
          ],
          "total": 0
        },
        "desc": ""
      }
    },
    "paymentListPaymentsResponseData": {
      "type": "object",
      "title": "ListPaymentsResponseData",
      "properties": {
        "results": {
          "type": "array",
          "title": "The results",
          "items": {
            "$ref": "#/definitions/paymentListPaymentsResponseDataResults"
          }
        },
        "total": {
          "type": "integer",
          "format": "int32",
          "title": "The total"
        }
      },
      "example": {
        "results": [
          {
            "amount": {
              "product": {
                "currency": "EUR",
                "price": 0
              },
              "reseller": {
                "currency": "EUR",
                "price": 0
              }
            },
            "confirmation_date": "",
            "creation_date": "2006-09-15 14:19:30",
            "id": 123,
            "is_processed": false,
            "method": "",
            "payment_date": "2006-09-15 14:25:30",
            "status": "new",
            "type": "online"
          }
        ],
        "total": 0
      }
    },
    "paymentListPaymentsResponseDataResults": {
      "type": "object",
      "title": "ListPaymentsResponseDataResults",
      "properties": {
        "amount": {
          "title": "The amount",
          "$ref": "#/definitions/paymentPrices"
        },
        "confirmation_date": {
          "type": "string",
          "title": "The confirmation date"
        },
        "creation_date": {
          "type": "string",
          "title": "The creation date"
        },
        "id": {
          "type": "integer",
          "format": "int32",
          "title": "The id"
        },
        "is_processed": {
          "type": "boolean",
          "format": "boolean",
          "title": "Is processed"
        },
        "method": {
          "type": "string",
          "title": "The method"
        },
        "payment_date": {
          "type": "string",
          "title": "The payment date"
        },
        "status": {
          "type": "string",
          "title": "The status"
        },
        "type": {
          "type": "string",
          "title": "The type"
        }
      },
      "example": {
        "amount": {
          "product": {
            "currency": "EUR",
            "price": 0
          },
          "reseller": {
            "currency": "EUR",
            "price": 0
          }
        },
        "confirmation_date": "",
        "creation_date": "2006-09-15 14:19:30",
        "id": 123,
        "is_processed": false,
        "method": "",
        "payment_date": "2006-09-15 14:25:30",
        "status": "new",
        "type": "online"
      }
    },
    "paymentPrice": {
      "type": "object",
      "title": "Price",
      "properties": {
        "currency": {
          "type": "string",
          "title": "The currency"
        },
        "price": {
          "type": "number",
          "format": "double",
          "title": "The price"
        }
      },
      "example": {
        "currency": "EUR",
        "price": 0
      }
    },
    "paymentPrices": {
      "type": "object",
      "title": "Prices",
      "properties": {
        "product": {
          "title": "Price in product currency",
          "$ref": "#/definitions/paymentPrice"
        },
        "reseller": {
          "title": "Price in reseller currency",
          "$ref": "#/definitions/paymentPrice"
        }
      },
      "example": {
        "product": {
          "currency": "EUR",
          "price": 0
        },
        "reseller": {
          "currency": "EUR",
          "price": 0
        }
      }
    },
    "transactionListTransactionsResponse": {
      "type": "object",
      "title": "ListTransactionsResponse",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32",
          "title": "The code"
        },
        "data": {
          "title": "The data",
          "$ref": "#/definitions/transactionListTransactionsResponseData"
        },
        "desc": {
          "type": "string",
          "title": "The desc"
        },
        "maintenance": {
          "type": "boolean",
          "format": "boolean",
          "title": "The maintenance"
        },
        "warnings": {
          "type": "array",
          "title": "The warnings",
          "items": {
            "$ref": "#/definitions/errorWarning"
          }
        }
      },
      "example": {
        "code": 0,
        "data": {
          "results": [
            {
              "action": "NEW",
              "creation_date": "2006-09-13 16:19:05",
              "discount": 0,
              "exchange_rate": 0,
              "object_type": "",
              "price": {
                "product": {
                  "currency": "EUR",
                  "price": 0
                },
                "reseller": {
                  "currency": "EUR",
                  "price": 0
                }
              },
              "quantity": 1,
              "reference_id": 1,
              "setup": {
                "product": {
                  "currency": "EUR",
                  "price": 0
                },
                "reseller": {
                  "currency": "EUR",
                  "price": 0
                }
              },
              "subject": "",
              "total": {
                "product": {
                  "currency": "EUR",
                  "price": 0
                },
                "reseller": {
                  "currency": "EUR",
                  "price": 0
                }
              },
              "type": "transaction",
              "vat": 1
            }
          ],
          "total": 5389
        },
        "desc": ""
      }
    },
    "transactionListTransactionsResponseData": {
      "type": "object",
      "title": "ListTransactionsResponseData",
      "properties": {
        "results": {
          "type": "array",
          "title": "The results",
          "items": {
            "$ref": "#/definitions/transactionListTransactionsResponseDataResults"
          }
        },
        "total": {
          "type": "integer",
          "format": "int32",
          "title": "The total"
        }
      },
      "example": {
        "results": [
          {
            "action": "NEW",
            "creation_date": "2006-09-13 16:19:05",
            "discount": 0,
            "exchange_rate": 0,
            "object_type": "",
            "price": {
              "product": {
                "currency": "EUR",
                "price": 0
              },
              "reseller": {
                "currency": "EUR",
                "price": 0
              }
            },
            "quantity": 1,
            "reference_id": 1,
            "setup": {
              "product": {
                "currency": "EUR",
                "price": 0
              },
              "reseller": {
                "currency": "EUR",
                "price": 0
              }
            },
            "subject": "",
            "total": {
              "product": {
                "currency": "EUR",
                "price": 0
              },
              "reseller": {
                "currency": "EUR",
                "price": 0
              }
            },
            "type": "transaction",
            "vat": 1
          }
        ],
        "total": 5389
      }
    },
    "transactionListTransactionsResponseDataResults": {
      "type": "object",
      "title": "ListTransactionsResponseDataResults",
      "properties": {
        "action": {
          "type": "string",
          "title": "The action"
        },
        "creation_date": {
          "type": "string",
          "title": "The creation date"
        },
        "discount": {
          "type": "number",
          "format": "double",
          "title": "The discount"
        },
        "exchange_rate": {
          "type": "number",
          "format": "double",
          "title": "The exchange rate"
        },
        "object_type": {
          "type": "string",
          "title": "The object type"
        },
        "price": {
          "title": "The price",
          "$ref": "#/definitions/transactionPrices"
        },
        "quantity": {
          "type": "integer",
          "format": "int32",
          "title": "The quantity"
        },
        "reference_id": {
          "type": "integer",
          "format": "int32",
          "title": "The reference id"
        },
        "setup": {
          "title": "The setup",
          "$ref": "#/definitions/transactionPrices"
        },
        "subject": {
          "type": "string",
          "title": "The subject"
        },
        "total": {
          "title": "The total",
          "$ref": "#/definitions/transactionPrices"
        },
        "type": {
          "type": "string",
          "title": "The type"
        },
        "vat": {
          "type": "integer",
          "format": "int32",
          "title": "The vat"
        }
      },
      "example": {
        "action": "NEW",
        "creation_date": "2006-09-13 16:19:05",
        "discount": 0,
        "exchange_rate": 0,
        "object_type": "",
        "price": {
          "product": {
            "currency": "EUR",
            "price": 0
          },
          "reseller": {
            "currency": "EUR",
            "price": 0
          }
        },
        "quantity": 1,
        "reference_id": 1,
        "setup": {
          "product": {
            "currency": "EUR",
            "price": 0
          },
          "reseller": {
            "currency": "EUR",
            "price": 0
          }
        },
        "subject": "",
        "total": {
          "product": {
            "currency": "EUR",
            "price": 0
          },
          "reseller": {
            "currency": "EUR",
            "price": 0
          }
        },
        "type": "transaction",
        "vat": 1
      }
    },
    "transactionPrice": {
      "type": "object",
      "title": "Price",
      "properties": {
        "currency": {
          "type": "string",
          "title": "The currency"
        },
        "price": {
          "type": "number",
          "format": "double",
          "title": "The price"
        }
      },
      "example": {
        "currency": "EUR",
        "price": 0
      }
    },
    "transactionPrices": {
      "type": "object",
      "title": "Prices",
      "properties": {
        "product": {
          "title": "Price in product currency",
          "$ref": "#/definitions/transactionPrice"
        },
        "reseller": {
          "title": "Price in reseller currency",
          "$ref": "#/definitions/transactionPrice"
        }
      },
      "example": {
        "product": {
          "currency": "EUR",
          "price": 0
        },
        "reseller": {
          "currency": "EUR",
          "price": 0
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}